### ISSUE TITLE
Youtube-sr and Player.js error

### ISSUE THREAD

**Issue by SLINIcraftet204** [ZerioDev/Music-bot#106]
Hey i've installed the bot but when I want to start this Error shows up:

```
/../../Music-bot/node_modules/youtube-sr/build/main.js:69
                                    url: item.channel.thumbnails?.default.url,
                                                                 ^

SyntaxError: Unexpected token .
    at Module._compile (internal/modules/cjs/loader.js:723:23)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (../../Music-bot/node_modules/discord-player/src/Player.js:3:14)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
```
Can you help me?

**Comment by AnshhSingh** [comment]
make sure you are using Nodejs v14 then it should work fine

**Comment by SLINIcraftet204** [comment]
Hey thanks for reply, I upgrades my NodeJS and it works now fine. My actually Version is now 14.15.0...
Thank you for help

PS: very cool written Bot :)
