### ISSUE TITLE
highestaudio ytdl-core throw an error

### ISSUE THREAD

**Issue by SLINIcraftet204** [ZerioDev/Music-bot#107]
how can I fix this Error?
```
events.js:292
      throw er; // Unhandled 'error' event
      ^

Error: No such format found: highestaudio
    at Object.exports.chooseFormat (/home/../Music-bot/node_modules/ytdl-core/lib/format-utils.js:148:11)
    at downloadFromInfoCallback (/home/../Music-bot/node_modules/ytdl-core/lib/index.js:85:26)
    at /home/../Music-bot/node_modules/ytdl-core/lib/index.js:20:5
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
Emitted 'error' event on Encoder instance at:
    at emitErrorNT (internal/streams/destroy.js:106:8)
    at emitErrorCloseNT (internal/streams/destroy.js:74:3)
    at processTicksAndRejections (internal/process/task_queues.js:80:21)
```
thanks for the future Replys adn thanks to everyone for help <3

**Comment by ZerioDev** [comment]
Hey !
You can try to update `discord-player` !
