### ISSUE TITLE
Youtube-sr Error

### ISSUE THREAD

**Issue by NikiRakshu** [ZerioDev/Music-bot#112]
```
node_modules\youtube-sr\build\main.js:69
                                    url: item.channel.thumbnails?.default.url,
```
* How to Fix This ?

**Comment by NikiRakshu** [comment]
```
D:\bot\main>node index.js
D:\bot\main>node_modules\youtube-sr\build\main.js:69
                                    url: item.channel.thumbnails?.default.url,
                                                                 ^

SyntaxError: Unexpected token '.'
←[90m    at wrapSafe (internal/modules/cjs/loader.js:1053:16)←[39m
←[90m    at Module._compile (internal/modules/cjs/loader.js:1101:27)←[39m
←[90m    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1157:10)←[39m
←[90m    at Module.load (internal/modules/cjs/loader.js:985:32)←[39m
←[90m    at Function.Module._load (internal/modules/cjs/loader.js:878:14)←[39m
←[90m    at Module.require (internal/modules/cjs/loader.js:1025:19)←[39m
←[90m    at require (internal/modules/cjs/helpers.js:72:18)←[39m
    at Object.<anonymous> (D:\AuricMusicmain-main\auric\node_modules\←[4mdiscord-player←[24m\src\Player.js:3:14)
←[90m    at Module._compile (internal/modules/cjs/loader.js:1137:30)←[39m
←[90m    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1157:10)←[39m
```

**Comment by ZerioDev** [comment]
You need to update Nodejs to `v.14.0` !
