### ISSUE TITLE
Not finding Discord module

### ISSUE THREAD

**Issue by proudparrot2** [ZerioDev/Music-bot#116]
Hi,
I am hosting my bot on https://replit.com but when I installed `npm install discord.js` and it said:

```
const client = new Discord.Client();
               ^

ReferenceError: Discord is not defined
    at Object.<anonymous> (/home/runner/Notelify/index.js:2:16)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12)
    at internal/main/run_main_module.js:17:47
```

Here is my code if you need reference --> https://replit.com/@ParrotDev/Notelify

**Comment by 0gGhost** [comment]
Hello, 

On Line 2 change the `Discord.Client` to `discord.Client` - So remove the capital `d`

That will sort the issue :)
Thanks.
