### ISSUE TITLE
error code: 403

### ISSUE THREAD

**Issue by DarkQuerTHG** [ZerioDev/Music-bot#150]
```
events.js:352
throw er; // Unhandled 'error' event
^
 
MinigetError: Status code: 403
  at ClientRequest.<anonymous> (/app/node_modules/miniget/dist/index.js:211:27)
  at Object.onceWrapper (events.js:482:26)
  at ClientRequest.emit (events.js:375:28)
  at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:647:27)
  at HTTPParser.parserOnHeadersComplete (_http_common.js:126:17)
  at HTTPParser.execute (<anonymous>)
  at TLSSocket.socketOnData (_http_client.js:515:22)
  at TLSSocket.emit (events.js:375:28)
  at addChunk (internal/streams/readable.js:290:12)
  at readableAddChunk (internal/streams/readable.js:265:9)
Emitted 'error' event on Encoder instance at:
  at emitErrorNT (internal/streams/destroy.js:106:8)
  at emitErrorCloseNT (internal/streams/destroy.js:74:3)
  at processTicksAndRejections (internal/process/task_queues.js:82:21) {
 statusCode: 403
}
```
I still have so recently what I can do about it. I host a bot by heroku.

**Comment by MaxTechnics** [comment]
HTTP 403 means forbidden, so either heroku is blacklisted somewhere, or you aren't using the right api keys. 
Just like on some other issues here, heroku is not meant for hosting discord bots. And is not a very reliable way of doing so. You should really consider a local host, or a service with more support (like repl.it. However, putting api keys in .env and adding code to support this will be needed)

**Comment by DarkQuerTHG** [comment]
Do you know how to add such code to .env in this project? Is it possible at all?

**Comment by MaxTechnics** [comment]
There are a few pull requests like #100 you can base yourself off.
