### ISSUE TITLE
baka idk wtf this is

### ISSUE THREAD

**Issue by T0TOR** [ZerioDev/Music-bot#157]
SyntaxError: Unexpected token '}'
    at wrapSafe (internal/modules/cjs/loader.js:1001:16)
    at Module._compile (internal/modules/cjs/loader.js:1049:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:14)
    at Module.require (internal/modules/cjs/loader.js:974:19)
    at require (internal/modules/cjs/helpers.js:92:18)
    at C:\Users\darkg\Downloads\Music-bot-master\Music-bot-master\index.js:18:25
    at Array.forEach (<anonymous>)
    at Object.<anonymous> (C:\Users\darkg\Downloads\Music-bot-master\Music-bot-master\index.js:14:30)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! music-bot@5.0.0 start: `node index.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the music-bot@5.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\darkg\AppData\Roaming\npm-cache\_logs\2021-06-25T13_45_58_916Z-debug.log
PS C:\Users\darkg\Downloads\Music-bot-master\Music-bot-master>

**Comment by T0TOR** [comment]
[2021-06-25T13_43_10_845Z-debug.log](https://github.com/ZerioDev/Music-bot/files/6716563/2021-06-25T13_43_10_845Z-debug.log)
debug log

**Comment by MaxTechnics** [comment]
You're likely having issues with an incorrectly formatted package.json

**Comment by revot334** [comment]
token is not vailed
