### ISSUE TITLE
TypeError: event.bind is not a function

### ISSUE THREAD

**Issue by Reloadee** [ZerioDev/Music-bot#168]
TypeError: event.bind is not a function
    at /home/runner/Speaky/index.js:37:48
    at Script.runInContext (vm.js:130:18)
    at Object.<anonymous> (/run_dir/interp.js:209:20)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:60:12)
    at internal/main/run_main_module.js:17:47

**Comment by revot334** [comment]
fixed! update bot!
