### ISSUE TITLE
Error code 410 

### ISSUE THREAD

**Issue by MantisToboggan2** [ZerioDev/Music-bot#169]
I keep getting error code 410 when ever someone skips a song in my server and the bot just says The music is starting.... please wait!!

MinigetError: Status code: 410
    at ClientRequest.<anonymous> (E:\Discord bots\MAIN\MantisBot\node_modules\miniget\dist\index.js:211:27)
    at Object.onceWrapper (events.js:482:26)
    at ClientRequest.emit (events.js:375:28)
    at HTTPParser.parserOnIncomingClient (_http_client.js:647:27)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:126:17)
    at TLSSocket.socketOnData (_http_client.js:515:22)
    at TLSSocket.emit (events.js:375:28)
    at addChunk (internal/streams/readable.js:290:12)
    at readableAddChunk (internal/streams/readable.js:265:9)
    at TLSSocket.Readable.push (internal/streams/readable.js:204:10)
Emitted 'error' event on Encoder instance at:
    at emitErrorNT (internal/streams/destroy.js:106:8)
    at emitErrorCloseNT (internal/streams/destroy.js:74:3)
    at processTicksAndRejections (internal/process/task_queues.js:82:21) {
  statusCode: 410
}

E:\Discord bots\MAIN\MantisBot>pause
Press any key to continue . . .

**Comment by T-Six** [comment]
Same here, no clue how to fix it.

**Comment by T-Six** [comment]
I'm not too good with all this yet. But I had the same issue and I found out that when I remade the bot (just a fresh new one in a different directory), it ran again. I'm not sure what exactly caused the issue. I believe there's been some updates.

Sorry for the lack of technical explanation, but I figured I'd share how I managed to fix it.

**Comment by Noman17-tect** [comment]
yup also getting this error.

**Comment by DaSussy** [comment]
guys, this bot is outdated

**Comment by revot334** [comment]
fixed in new bot :) you should update
