### ISSUE TITLE
Can I run this bot with repl.it?

### ISSUE THREAD

**Issue by lucastv52** [ZerioDev/Music-bot#188]
I'm trying to run the bot with the site repl.it, but it's not working. Is it possible? If no, how do I run other programs?

**Comment by JaedonLau** [comment]
I use replit to run the bot. But whats the error

**Comment by cristyanul** [comment]
```
/home/runner/Music-bot/node_modules/discord.js/src/rest/RESTManager.js:32
    const token = this.client.token ?? this.client.accessToken;
                                     ^

SyntaxError: Unexpected token '?'
    at wrapSafe (internal/modules/cjs/loader.js:915:16)
    at Module._compile (internal/modules/cjs/loader.js:963:27)
```

**Comment by Xaypanya** [comment]
host it with heroku working perfectly

**Comment by JaedonLau** [comment]
He didn't say how to host it, he is asking can he run he bot with repl.it

**Comment by Xaypanya** [comment]
> He didn't say how to host it, he is asking can he run he bot with repl.it

Yep, It's not working to host with repl.it and He asking for other program so I suggest him to host with Heroku instead. What's wrong?

**Comment by JaedonLau** [comment]
You can't host it with heroku. Its not a hosting site, use uptimerobot for repl.it instead. (And also repl.it free hosting is illegal so you may only use uptimerobot to host it)

**Comment by revot334** [comment]
this is not recommended because  of low ram and cpu
