### ISSUE TITLE
AbortController is not defined

### ISSUE THREAD

**Issue by CEKIKOFGAMERS** [ZerioDev/Music-bot#190]
```PS D:\MetroGamersRP\Music-bot> node main.js
Loading events...
-> Loaded event messageCreate
-> Loaded event ready
Loading commands...
-> Loaded command help
-> Loaded command ping
-> Loaded command back
-> Loaded command clear
-> Loaded command filter
-> Loaded command loop
-> Loaded command nowplaying
-> Loaded command pause
-> Loaded command play
-> Loaded command queue
-> Loaded command resume
-> Loaded command save
-> Loaded command seek
-> Loaded command shuffle
-> Loaded command skip
-> Loaded command stop
-> Loaded command volume
(node:6808) UnhandledPromiseRejectionWarning: ReferenceError: AbortController is not defined
    at RequestHandler.execute (D:\MetroGamersRP\Music-bot\node_modules\discord.js\src\rest\RequestHandler.js:172:15)
    at RequestHandler.execute (D:\MetroGamersRP\Music-bot\node_modules\discord.js\src\rest\RequestHandler.js:176:19)
    at RequestHandler.push (D:\MetroGamersRP\Music-bot\node_modules\discord.js\src\rest\RequestHandler.js:50:25)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async WebSocketManager.connect (D:\MetroGamersRP\Music-bot\node_modules\discord.js\src\client\websocket\WebSocketManager.js:128:9)    
    at async Client.login (D:\MetroGamersRP\Music-bot\node_modules\discord.js\src\client\Client.js:245:7)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:6808) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
(node:6808) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.``` i get this error while running main.js but no error in previous version

**Comment by Ch1sKey** [comment]
Update node to v16 would help I suppose

**Comment by revot334** [comment]
fixed in update
