### ISSUE TITLE
Bot crashes randomly

### ISSUE THREAD

**Issue by PanConKisu** [ZerioDev/Music-bot#200]
```events.js:377
      throw er; // Unhandled 'error' event
      ^

MinigetError: Status code: 403
    at ClientRequest.<anonymous> (C:\Users\cooki\OneDrive\Escritorio\FDE Music Bot 2\node_modules\miniget\dist\index.js:210:27)
    at Object.onceWrapper (events.js:520:26)
    at ClientRequest.emit (events.js:400:28)
    at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:647:27)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:126:17)
    at TLSSocket.socketOnData (_http_client.js:515:22)
    at TLSSocket.emit (events.js:400:28)
    at addChunk (internal/streams/readable.js:290:12)
    at readableAddChunk (internal/streams/readable.js:265:9)
    at TLSSocket.Readable.push (internal/streams/readable.js:204:10)
Emitted 'error' event on Encoder instance at:
    at emitErrorNT (internal/streams/destroy.js:106:8)
    at emitErrorCloseNT (internal/streams/destroy.js:74:3)
    at processTicksAndRejections (internal/process/task_queues.js:82:21) {
  statusCode: 403
}

**Comment by PanConKisu** [comment]
> Are you using a hosting service like Repl.it or Heroku?

nope, i'm using a local server

**Comment by dragonfirefox** [comment]
That's miniget error while YouTube blocking or miniget didn't got any results, it's normal problem with ytdl bots, use listen process errors to handle this type errors.

**Comment by revot334** [comment]
fixed in v7
