### ISSUE TITLE
statusCode: 'InvalidArgType'

### ISSUE THREAD

**Issue by Lizan45** [ZerioDev/Music-bot#217]
InvalidArgType: [InvalidArgType] Channel type must be GUILD_VOICE or GUILD_STAGE_VOICE, got voice!
    at new PlayerError (C:\Users\lisan\workspace\Roxanne\node_modules\discord-player\dist\Structures\PlayerError.js:28:15)
    at Queue.<anonymous> (C:\Users\lisan\workspace\Roxanne\node_modules\discord-player\dist\Structures\Queue.js:156:23)   
    at Generator.next (<anonymous>)
    at C:\Users\lisan\workspace\Roxanne\node_modules\discord-player\dist\Structures\Queue.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (C:\Users\lisan\workspace\Roxanne\node_modules\discord-player\dist\Structures\Queue.js:4:12)
    at Queue.connect (C:\Users\lisan\workspace\Roxanne\node_modules\discord-player\dist\Structures\Queue.js:151:16)
    at Object.run (C:\Users\lisan\workspace\Roxanne\commands\general\play.js:24:42)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) {
  createdAt: 2021-12-07T02:37:14.620Z,
  statusCode: 'InvalidArgType'
}

**Comment by Lizan45** [comment]
This happen when i want reproduce something.

**Comment by revot334** [comment]
should be fixed with v7
