### ISSUE TITLE
Error when playing a song on the bot!

### ISSUE THREAD

**Issue by Fluffik3666** [ZerioDev/Music-bot#265]
I am running the bot on DigitalOcean, here is the error I get when doing /play:

[music-bot] [2023-04-06 19:56:16] -> Ready on 1 servers for a total of 1 users
[music-bot] [2023-04-06 19:56:43] /workspace/node_modules/@discordjs/rest/dist/index.js:640
[music-bot] [2023-04-06 19:56:43]       throw new DiscordAPIError(data, "code" in data ? data.code : data.error, status, method, url, requestData);
[music-bot] [2023-04-06 19:56:43]             ^
[music-bot] [2023-04-06 19:56:43] 
[music-bot] [2023-04-06 19:56:43] DiscordAPIError[10062]: Unknown interaction
[music-bot] [2023-04-06 19:56:43]     at handleErrors (/workspace/node_modules/@discordjs/rest/dist/index.js:640:13)
[music-bot] [2023-04-06 19:56:43]     at processTicksAndRejections (node:internal/process/task_queues:96:5)
[music-bot] [2023-04-06 19:56:43]     at async BurstHandler.runRequest (/workspace/node_modules/@discordjs/rest/dist/index.js:736:23)
[music-bot] [2023-04-06 19:56:43]     at async REST.request (/workspace/node_modules/@discordjs/rest/dist/index.js:1387:22)
[music-bot] [2023-04-06 19:56:43]     at async ChatInputCommandInteraction.deferReply (/workspace/node_modules/discord.js/src/structures/interfaces/InteractionResponses.js:69:5)
[music-bot] [2023-04-06 19:56:43]     at async Object.execute (/workspace/commands/music/play.js:17:2) {
[music-bot] [2023-04-06 19:56:43]   requestBody: { files: undefined, json: { type: 5, data: { flags: undefined } } },
[music-bot] [2023-04-06 19:56:43]   rawError: { message: 'Unknown interaction', code: 10062 },
[music-bot] [2023-04-06 19:56:43]   code: 10062,
[music-bot] [2023-04-06 19:56:43]   status: 404,
[music-bot] [2023-04-06 19:56:43]   method: 'POST',
[music-bot] [2023-04-06 19:56:43]   url: 'https://discord.com/api/v10/interactions/1093625355522289805/aW50ZXJhY3Rpb246MTA5MzYyNTM1NTUyMjI4OTgwNTpRSVl3bHJYRGdCR0dySlYyaDNTMVFHOXNtNm1qRWo4RUF3TmpDaFFKeU9Wbk9BRzBYOFFGdmxIeFFiQTBoZWNFYVpFTDFOOGZiWlBTSm41bUxST1NKVFN2T0JCdXpiVlkwekxiNlJWenlQMUU2NUxhY29ZRzB1N0dOZDYzdUVzSw/callback'
[music-bot] [2023-04-06 19:56:43] }
[music-bot] [2023-04-06 19:56:43] npm notice 
[music-bot] [2023-04-06 19:56:43] npm notice New major version of npm available! 8.19.4 -> 9.6.4
[music-bot] [2023-04-06 19:56:43] npm notice Changelog: <https://github.com/npm/cli/releases/tag/v9.6.4>
[music-bot] [2023-04-06 19:56:43] npm notice Run `npm install -g npm@9.6.4` to update!
[music-bot] [2023-04-06 19:56:43] npm notice

**Comment by revot334** [comment]
Hello @Fluffik3666 can you check what node version you are using by running: node -v

**Comment by Fluffik3666** [comment]
Sure!

**Comment by revot334** [comment]
Can you show me what is says

**Comment by Fluffik3666** [comment]
k

**Comment by Fluffik3666** [comment]
[2023-04-06 20:01:31] -> [Loaded Command] volume
[2023-04-06 20:01:32] Logged to the client Helper.AI Music
[2023-04-06 20:01:32] -> Ready on 1 servers for a total of 1 users
[2023-04-06 20:02:04] node:events:491
[2023-04-06 20:02:04]       throw er; // Unhandled 'error' event
[2023-04-06 20:02:04]       ^
[2023-04-06 20:02:04] 
[2023-04-06 20:02:04] DiscordAPIError[10062]: Unknown interaction
[2023-04-06 20:02:04]     at handleErrors (/workspace/node_modules/@discordjs/rest/dist/index.js:640:13)
[2023-04-06 20:02:04]     at processTicksAndRejections (node:internal/process/task_queues:96:5)
[2023-04-06 20:02:04]     at async BurstHandler.runRequest (/workspace/node_modules/@discordjs/rest/dist/index.js:736:23)
[2023-04-06 20:02:04]     at async REST.request (/workspace/node_modules/@discordjs/rest/dist/index.js:1387:22)
[2023-04-06 20:02:04]     at async ChatInputCommandInteraction.reply (/workspace/node_modules/discord.js/src/structures/interfaces/InteractionResponses.js:111:5)
[2023-04-06 20:02:04] Emitted 'error' event on Client instance at:
[2023-04-06 20:02:04]     at emitUnhandledRejectionOrErr (node:events:394:10)
[2023-04-06 20:02:04]     at processTicksAndRejections (node:internal/process/task_queues:85:21) {
[2023-04-06 20:02:04]   requestBody: {
[2023-04-06 20:02:04]     files: [],
[2023-04-06 20:02:04]     json: {
[2023-04-06 20:02:04]       type: 4,
[2023-04-06 20:02:04]       data: {
[2023-04-06 20:02:04]         content: undefined,
[2023-04-06 20:02:04]         tts: false,
[2023-04-06 20:02:04]         nonce: undefined,
[2023-04-06 20:02:04]         embeds: [
[2023-04-06 20:02:04]           {
[2023-04-06 20:02:04]             color: 16711680,
[2023-04-06 20:02:04]             description: '❌ | You are not in a Voice Channel'
[2023-04-06 20:02:04]           }
[2023-04-06 20:02:04]         ],
[2023-04-06 20:02:04]         components: undefined,
[2023-04-06 20:02:04]         username: undefined,
[2023-04-06 20:02:04]         avatar_url: undefined,
[2023-04-06 20:02:04]         allowed_mentions: undefined,
[2023-04-06 20:02:04]         flags: 64,
[2023-04-06 20:02:04]         message_reference: undefined,
[2023-04-06 20:02:04]         attachments: undefined,
[2023-04-06 20:02:04]         sticker_ids: undefined,
[2023-04-06 20:02:04]         thread_name: undefined
[2023-04-06 20:02:04]       }
[2023-04-06 20:02:04]     }
[2023-04-06 20:02:04]   },
[2023-04-06 20:02:04]   rawError: { message: 'Unknown interaction', code: 10062 },
[2023-04-06 20:02:04]   code: 10062,
[2023-04-06 20:02:04]   status: 404,
[2023-04-06 20:02:04]   method: 'POST',
[2023-04-06 20:02:04]   url: 'https://discord.com/api/v10/interactions/1093626701143093301/aW50ZXJhY3Rpb246MTA5MzYyNjcwMTE0MzA5MzMwMTpYd0Y3S084WFhSMW1VQzYxQmlkY0Z0bHZMUndjc0M2YVRZVnlncHZXSnVZRXZibGZTZHlwb0ZpWDdIc21ESVFkcDhwWnprWlFuc1FyNldORjEzT1VQTzBuYVZaOW1yNGZ6RDVtNG1xcE9lSG5mb094UDJHZE83YzBVY2Q4c2pUbA/callback'
[2023-04-06 20:02:04] }
[2023-04-06 20:02:04] npm notice 
[2023-04-06 20:02:04] npm notice New major version of npm available! 8.19.4 -> 9.6.4
[2023-04-06 20:02:04] npm notice Changelog: <https://github.com/npm/cli/releases/tag/v9.6.4>
[2023-04-06 20:02:04] npm notice Run `npm install -g npm@9.6.4` to update!
[2023-04-06 20:02:04] npm notice 
[]

**Comment by Fluffik3666** [comment]
I was in a voice channel tho

**Comment by revot334** [comment]
known problem i will push a fix

**Comment by Fluffik3666** [comment]
**### made it work** @revot334
