### ISSUE TITLE
Another error

### ISSUE THREAD

**Issue by Satyaki34** [ZerioDev/Music-bot#273]
```
D:\Music-bot-master\src\events.js:4
    console.log(`Error emitted from the queue ${error.message}`);
                                                      ^

TypeError: Cannot read properties of undefined (reading 'message')
    at _Player.<anonymous> (D:\Music-bot-master\src\events.js:4:55)
    at _Player.emit (node:events:513:28)
    at _Player.emit (D:\Music-bot-master\node_modules\discord-player\dist\index.js:207:18)
    at D:\Music-bot-master\node_modules\discord-player\dist\index.js:2537:16
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
```
    i install everything with yarn,but still get this error...

**Comment by Alphaegen** [comment]
You should switch to the beta branch using `git checkout "beta-(Bugs-are-expected)"`. The main branch has issues.
