### ISSUE TITLE
Not working (beta branch): Skipping extractors execution since zero extractors were registered

### ISSUE THREAD

**Issue by Alpaca0x0** [ZerioDev/Music-bot#280]
When I use "`play`" command, the bot **doesn't** join voice chanel(no music of course), and the console show me the message "`Skipping extractors execution since zero extractors were registered`".
So I try to use "`--trace-warnings`" argument in "`node .`" command, then console show me this:

```
(node:197495) [NoExtractors] Warning: Skipping extractors execution since zero extractors were registered
    at Util.warn (/home/alca/services/discord-bot/EDoT/node_modules/discord-player/dist/index.js:187:13)
    at ExtractorExecutionContext.run (/home/alca/services/discord-bot/EDoT/node_modules/discord-player/dist/index.js:456:12)
    at _Player.search (/home/alca/services/discord-bot/EDoT/node_modules/discord-player/dist/index.js:3128:42)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Object.execute (/home/alca/services/discord-bot/EDoT/commands/music/play.js:18:21)
```

How should I do to fix this :(

---

- OS: `Ubuntu 22.04.1 LTS`
- Package Manager: `Yarn`

**Comment by wildgoose2** [comment]
I have the same issue on Windows using both yarn and npm as my package manager. Clean installs don't seem to fix the problem.

**Comment by skdhg** [comment]
Add this line in your main file

```js
player.extractors.loadDefault();
```

**Comment by Alpaca0x0** [comment]
> Add this line in your main file
> 
> ```js
> player.extractors.loadDefault();
> ```

It's working now !
Thank you :D Good answer.
