### ISSUE TITLE
Bot not playing age restricted content from youtube

### ISSUE THREAD

**Issue by Zal-com** [ZerioDev/Music-bot#282]
Bot crashes when trying to read music from age-restricted youtube URL

```
/home/pi/bot/node_modules/discord-player/dist/index.js:985
        const error = new Error("Could not extract stream for this track");
                      ^

Error: Could not extract stream for this track
    at GuildQueuePlayerNode.play (/home/pi/bot/node_modules/discord-player/dist/index.js:985:23)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Object.execute (/home/pi/bot/commands/music/play.js:50:33)
```

**Comment by itsjustyryr** [comment]
Hey! Are you sure did you do yarn install?
