### ISSUE TITLE
Bot go offline automatically after playing a song

### ISSUE THREAD

**Issue by WistfulPerson** [ZerioDev/Music-bot#293]
Bot go offline automatically after playing a song and doesn't even play a song after doing /play it enters the room and go offline without playing the song or doing anything

**Comment by marcelog09** [comment]
+UP

**Comment by WearSoLiD** [comment]
Same issue

nodejs log:

E:\ErgoProxy\node_modules\discord-player\dist\index.js:591
      const exception = new err.type(err.createError(...args));
                        ^

ERR_NO_RESULT: Could not extract stream for this track

evalmachine.<anonymous>:426
Ama=function(a,b,c,d){var e=null;switch(b){case "JSON":try{var f=c.responseText}catch(h){throw d=Error("Error reading responseText"),d.params=a,oC(d),h;}a=c.getResponseHeader("Content-Type")||"";f&&0<=a.indexOf("json")&&(")]};Ila(ncode);

   ^^^^^^^^^^^^^^^^

SyntaxError: Invalid or unexpected token
    at new Script (node:vm:100:7)
    at exports.decipherFormats (E:\ErgoProxy\node_modules\ytdl-core\lib\sig.js:116:51)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Promise.all (index 0)
    at async exports.getInfo (E:\ErgoProxy\node_modules\ytdl-core\lib\info.js:401:17)
    at Proxy.<anonymous> (E:\ErgoProxy\node_modules\discord-player\dist\index.js:591:25)
    at #throw (E:\ErgoProxy\node_modules\discord-player\dist\index.js:1884:80)
    at GuildQueuePlayerNode.play (E:\ErgoProxy\node_modules\discord-player\dist\index.js:1829:56)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Object.execute (E:\ErgoProxy\commands\music\play.js:62:33)

Node.js v18.16.0

**Comment by Nickeldon** [comment]
Hi there, your issues are more likely due to the issue affecting every ytdl-core installations at the time. 

If you are already part of our discord community, I invite you to follow this issue thread in order to fix your problem:

https://discord.com/channels/773639842449850368/1150095560200687690

@Nikkerudon

**Comment by marcelog09** [comment]
> Hi there, your issues are more likely due to the issue affecting every ytdl-core installations at the time.
> 
> If you are already part of our discord community, I invite you to follow this issue thread in order to fix your problem:
> 
> https://discord.com/channels/773639842449850368/1150095560200687690
> 
> @Nikkerudon

How do we join this community?

**Comment by WistfulPerson** [comment]
thanks for the help it solved the problem :)
