### ISSUE TITLE
YoutubeExtractor

### ISSUE THREAD

**Issue by princew7** [ZerioDev/Music-bot#325]
運行機器人後的提示
(node:25356) Warning: YoutubeExtractor uses scraping-based streaming libraries which is known to be unstable at times.
An alternative is to use discord-player-youtubei https://npm.im/discord-player-youtubei
View this GitHub issue for more information: https://github.com/Androz2091/discord-player/issues/1922
(Use `node --trace-warnings ...` to show where the warning was created)
某些歌曲在抓取上確實存在問題

**Comment by LND237** [comment]
Can you please provide where the warning was created? It would be helpful.

**Comment by BoredKevin** [comment]
Hi, I had received this error as well, I have provided the error below and a screenshot

`(node:2112406) Warning: YoutubeExtractor uses scraping-based streaming libraries which is known to be unstable at times.
An alternative is to use discord-player-youtubei https://npm.im/discord-player-youtubei
View this GitHub issue for more information: https://github.com/Androz2091/discord-player/issues/1922
(Use `node --trace-warnings ...` to show where the warning was created)`

![image](https://github.com/user-attachments/assets/f129a5d9-4113-4870-bf9e-efb63136cc35)

**Comment by princew7** [comment]
> Hi, I had received this error as well, I have provided the error below and a screenshot
> 
> `(node:2112406) Warning: YoutubeExtractor uses scraping-based streaming libraries which is known to be unstable at times. An alternative is to use discord-player-youtubei https://npm.im/discord-player-youtubei View this GitHub issue for more information: https://github.com/Androz2091/discord-player/issues/1922 (Use `node --trace-warnings ...` to show where the warning was created)`
> 
> ![image](https://private-user-images.githubusercontent.com/107290249/352132488-f129a5d9-4113-4870-bf9e-efb63136cc35.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE5MTk4ODgsIm5iZiI6MTcyMTkxOTU4OCwicGF0aCI6Ii8xMDcyOTAyNDkvMzUyMTMyNDg4LWYxMjlhNWQ5LTQxMTMtNDg3MC1iZjllLWVmYjYzMTM2Y2MzNS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzI1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcyNVQxNDU5NDhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mZGUyZjI4MDU4MWUzNDIzYzk5OTdhZDQ0YWFmMTE2MDBjZjZhYmExYWM3OTFjZDRkNGZjOGU4YzYxYzgzY2E5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.MdufRII96QE9NsNe7tZ5Bortr1S59OmLbdcuv80KP08)

Thanks, same issue

**Comment by StefanoCastro** [comment]
not really helpfull, but same

**Comment by LND237** [comment]
@BoredKevin Can you please run the bot with the ```node --trace-warnings``` to locate where the warning is created?

**Comment by BoredKevin** [comment]
Here is what I got:
```
(node:3932631) Warning: YoutubeExtractor uses scraping-based streaming libraries which is known to be unstable at times.
An alternative is to use discord-player-youtubei https://npm.im/discord-player-youtubei
View this GitHub issue for more information: https://github.com/Androz2091/discord-player/issues/1922
    at _YoutubeExtractor.activate (/home/musicbot/lethal-boombox/node_modules/@discord-player/extractor/dist/index.js:563:13)
    at async _ExtractorExecutionContext.register (/home/musicbot/lethal-boombox/node_modules/discord-player/dist/index.js:1340:7)
```

![image](https://github.com/user-attachments/assets/bd65382a-bd05-4fdf-bee2-c5b9dac01e9f)

**Comment by LND237** [comment]
So this error comes from the ```YoutubeExtractor``` which the ```discord-player``` package uses, We will need to replace that with the ```Discord Player YouTubei``` package and modify the code to solve this.

**Comment by malitha22** [comment]
can you modify the code for discord player youtubei?

**Comment by LND237** [comment]
@malitha22 Kinda busy right now on other things

**Comment by LND237** [comment]
In https://github.com/Androz2091/discord-player/issues/1922 there are some implementations for the conversions but I haven't tested it yet.

**Comment by dev-shashwatt** [comment]
> can you modify the code for discord player youtubei?

i have modified and fixed it
