### ISSUE TITLE
Error Confirm you're not a Bot

### ISSUE THREAD

**Issue by SLINIcraftet204** [ZerioDev/Music-bot#331]
Hey,

I've installed the Bot correctly and become this error when I want to play some music from Spotify or Youtube. Can somebody explain how to fix this?

`Error: Sign in to confirm you’re not a bot
    at exports.playError (/root/Bots/NEWMUSIC-Bot/Music-bot/node_modules/@distube/ytdl-core/lib/utils.js:164:12)
    at exports.getBasicInfo (/root/Bots/NEWMUSIC-Bot/Music-bot/node_modules/@distube/ytdl-core/lib/info.js:46:25)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)>
Error emitted from the player <[ERR_NO_RESULT] Could not extract stream for this track`

My Node Version is 20.x LTS and I use Debian 12

**Comment by Nickeldon** [comment]
Look at this announcement: https://discord.com/channels/773639842449850368/784566240433274910/1253742564419436684
