### ISSUE TITLE
Can we work together

### ISSUE THREAD

**Issue by Unknownio** [ZerioDev/Music-bot#50]
pls , 🙏🙏

**Comment by ZerioDev** [comment]
Good evening 👋
What exactly do you want ?

**Comment by Unknownio** [comment]
to team up


and i have problem with the filters here is the error code

TypeError: Cannot convert undefined or null to object
    at Function.values (<anonymous>)
    at Object.execute (C:\Users\Acer\Desktop\Simple-Bot\commands\music\filter.js:16:39)
    at module.exports (C:\Users\Acer\Desktop\Simple-Bot\events\message.js:14:18)
    at Client.emit (events.js:327:22)
    at MessageCreateAction.handle (C:\Users\Acer\Desktop\Simple-Bot\node_modules\discord.js\src\client\actions\MessageCreate.js:31:14)
    at Object.module.exports [as MESSAGE_CREATE] (C:\Users\Acer\Desktop\Simple-Bot\node_modules\discord.js\src\client\websocket\handlers\MESSAGE_CREATE.js:4:32)
    at WebSocketManager.handlePacket (C:\Users\Acer\Desktop\Simple-Bot\node_modules\discord.js\src\client\websocket\WebSocketManager.js:384:31)
    at WebSocketShard.onPacket (C:\Users\Acer\Desktop\Simple-Bot\node_modules\discord.js\src\client\websocket\WebSocketShard.js:444:22)
    at WebSocketShard.onMessage (C:\Users\Acer\Desktop\Simple-Bot\node_modules\discord.js\src\client\websocket\WebSocketShard.js:301:10)
    at WebSocket.onMessage (C:\Users\Acer\Desktop\Simple-Bot\node_modules\ws\lib\event-target.js:132:16)

**Comment by Unknownio** [comment]
im looking to find people that like to program bots/apps because it looks cool and  make new friends im not bad at coding ,
if u like to chat my discord id is: YodaX#4079

**Comment by ZerioDev** [comment]
Hello 👋
I have a lot of pending friend requests.
I suggest you to join my Discord server. You can find the link in my profile or on this project.

**Comment by ZerioDev** [comment]
Hello 👋
I close this issue due to inactivity, do not hesitate to reopen one if necessary.
