### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by ThePronixowy** [ZerioDev/Music-bot#62]
When I try to join the voice channel with the play command, an error appears. Error: 

`(node:12900)` UnhandledPromiseRejectionWarning: TypeError: command.run is not a function
    at Client.<anonymous> (C:\Users\user\Desktop\Thunder Music\index.js:44:17)
    at Client.emit (events.js:315:20)
    at MessageCreateAction.handle (C:\Users\user\node_modules\discord.js\src\client\actions\MessageCreate.js:31:14)
    at Object.module.exports [as MESSAGE_CREATE] (C:\Users\user\node_modules\discord.js\src\client\websocket\handlers\MESSAGE_CREATE.js:4:32)
    at WebSocketManager.handlePacket (C:\Users\user\node_modules\discord.js\src\client\websocket\WebSocketManager.js:384:31)
    at WebSocketShard.onPacket (C:\Users\user\node_modules\discord.js\src\client\websocket\WebSocketShard.js:444:22)
    at WebSocketShard.onMessage (C:\Users\user\node_modules\discord.js\src\client\websocket\WebSocketShard.js:301:10)
    at WebSocket.onMessage (C:\Users\user\node_modules\ws\lib\event-target.js:132:16)
    at WebSocket.emit (events.js:315:20)
    at Receiver.receiverOnMessage (C:\Users\user\node_modules\ws\lib\websocket.js:825:20)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:12900) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:12900) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.`

**Comment by L0SER8228** [comment]
I think you have changed the **[message event](https://github.com/ZerioDev/Music-bot/blob/master/events/message.js)**
You did `command.run`
Change back it to `command.execute`
Hope this will work

**Comment by ThePronixowy** [comment]
I do not know where, here is the command (do not pay attention to the suppression of the command, messages): 

module.exports = {
    name: 'clear-queue',
    aliases: ['cq'],
    category: 'Music',
    utilisation: '{prefix}clear-queue',

    execute(client, message) {
        if (!message.member.voice.channel) return message.channel.send(`Dołącz na kanał głosowy!`);

        if (message.guild.me.voice.channel && message.member.voice.channel.id !== message.guild.me.voice.channel.id) return message.channel.send(`Nie jesteś na tym samym kanale głosowym!`);

        if (!client.player.getQueue(message)) return message.channel.send(`Żadna piosenka teraz nie leci!`);

        if (client.player.getQueue(message).tracks.length <= 1) return message.channel.send(`Jest tylko 1 piosenka w kolejce.`);

        client.player.clearQueue(message);

        message.channel.send(`Kolejka została wyczyszcona!`);
    },
};

**Comment by ThePronixowy** [comment]
Anyway, I changed to index.js but I have an error anyway I don't know why, I installed fs and dotenv and discord.js. Here is the error:

`(node:3676) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'play' of undefined
    at Object.execute (C:\Users\user\Desktop\Thunder Music\commands\komendy\play.js:14:23)
    at Client.<anonymous> (C:\Users\user\Desktop\Thunder Music\index.js:44:17)
    at Client.emit (events.js:315:20)
    at MessageCreateAction.handle (C:\Users\user\node_modules\discord.js\src\client\actions\MessageCreate.js:31:14)
    at Object.module.exports [as MESSAGE_CREATE] (C:\Users\user\node_modules\discord.js\src\client\websocket\handlers\MESSAGE_CREATE.js:4:32)
    at WebSocketManager.handlePacket (C:\Users\user\node_modules\discord.js\src\client\websocket\WebSocketManager.js:384:31)
    at WebSocketShard.onPacket (C:\Users\user\node_modules\discord.js\src\client\websocket\WebSocketShard.js:444:22)
    at WebSocketShard.onMessage (C:\Users\user\node_modules\discord.js\src\client\websocket\WebSocketShard.js:301:10)
    at WebSocket.onMessage (C:\Users\user\node_modules\ws\lib\event-target.js:132:16)
    at WebSocket.emit (events.js:315:20)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:3676) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:3676) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process
with a non-zero exit code.`

**Comment by Swarwerth** [comment]
Have you change anything in the code ?

**Comment by ThePronixowy** [comment]
no

**Comment by ThePronixowy** [comment]
only translate commands

**Comment by ZerioDev** [comment]
Closed for inactivity 🚫
