### ISSUE TITLE
I did everything clearly according to the instructions The bot simply enters the voice channel and nothing else happens

### ISSUE THREAD

**Issue by Imatl** [ZerioDev/Music-bot#65]
```(node:2504) UnhandledPromiseRejectionWarning: Error: FFmpeg/avconv not found!
    at Function.getInfo (D:\discord\Music-bot-master\node_modules\prism-media\src\core\FFmpeg.js:142:11)
    at Function.create (D:\discord\Music-bot-master\node_modules\prism-media\src\core\FFmpeg.js:155:38)
    at new FFmpeg (D:\discord\Music-bot-master\node_modules\prism-media\src\core\FFmpeg.js:44:27)
    at StreamDownloader (D:\discord\Music-bot-master\node_modules\discord-ytdl-core\index.js:45:24)
    at Promise (D:\discord\Music-bot-master\node_modules\discord-player\src\Player.js:681:31)
    at new Promise (<anonymous>)
    at Player._playYTDLStream (D:\discord\Music-bot-master\node_modules\discord-player\src\Player.js:667:16)
    at Player._playTrack (D:\discord\Music-bot-master\node_modules\discord-player\src\Player.js:747:14)
    at channel.join.then (D:\discord\Music-bot-master\node_modules\discord-player\src\Player.js:300:22)
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:2504) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:2504) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.```

**Comment by ZerioDev** [comment]
Hi 👋
Try to install `ffmpeg-static`, `npm i ffmpeg-static`.

**Comment by Imatl** [comment]
okay where downald module?
```(node:3788) UnhandledPromiseRejectionWarning: Error: Error: Cannot find module '@discordjs/opus'
Error: Cannot find module 'node-opus'
Error: Cannot find module 'opusscript'
    at Object.loader [as require] (D:\discord\Music-bot-master\node_modules\prism-media\src\util\loader.js:12:9)
    at loadOpus (D:\discord\Music-bot-master\node_modules\prism-media\src\opus\Opus.js:17:17)
    at new OpusStream (D:\discord\Music-bot-master\node_modules\prism-media\src\opus\Opus.js:46:10)
    at new Encoder (D:\discord\Music-bot-master\node_modules\prism-media\src\opus\Opus.js:149:5)
    at StreamDownloader (D:\discord\Music-bot-master\node_modules\discord-ytdl-core\index.js:59:18)
    at Promise (D:\discord\Music-bot-master\node_modules\discord-player\src\Player.js:681:31)
    at new Promise (<anonymous>)
    at Player._playYTDLStream (D:\discord\Music-bot-master\node_modules\discord-player\src\Player.js:667:16)
    at Player._playTrack (D:\discord\Music-bot-master\node_modules\discord-player\src\Player.js:747:14)
    at channel.join.then (D:\discord\Music-bot-master\node_modules\discord-player\src\Player.js:300:22)
(node:3788) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:3788) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by ZerioDev** [comment]
Also install `npm i node-opus` and `npm i opusscript`.

**Comment by Imatl** [comment]
![image](https://user-images.githubusercontent.com/77237650/104126788-32908100-5367-11eb-9081-03889b899e66.png)
thk you it worked

**Comment by ZerioDev** [comment]
No problem, have a good day 👍
