### ISSUE TITLE
Error: TypeError: Cannot read property 'find' of undefined when using the filter command

### ISSUE THREAD

**Issue by lucasfortheday** [ZerioDev/Music-bot#69]
### Steps to reproduce: 

1.  {prefix}play love (or any other title/url)
2.  {prefix}filter nightcore (or any other filter)
3. Bot instance crashes and prints the following error into the console:

`TypeError: Cannot read property 'find' of undefined
    at Object.execute (C:\Users\lutzl\Desktop\otis2\commands\music\filter.js:16:47)
    at module.exports (C:\Users\lutzl\Desktop\otis2\events\message.js:13:18)
    at Client.emit (node:events:376:20)
    at MessageCreateAction.handle (C:\Users\lutzl\Desktop\otis2\node_modules\discord.js\src\client\actions\MessageCreate.js:31:14)
    at Object.module.exports [as MESSAGE_CREATE] (C:\Users\lutzl\Desktop\otis2\node_modules\discord.js\src\client\websocket\handlers\MESSAGE_CREATE.js:4:32)
    at WebSocketManager.handlePacket (C:\Users\lutzl\Desktop\otis2\node_modules\discord.js\src\client\websocket\WebSocketManager.js:384:31)
    at WebSocketShard.onPacket (C:\Users\lutzl\Desktop\otis2\node_modules\discord.js\src\client\websocket\WebSocketShard.js:444:22)
    at WebSocketShard.onMessage (C:\Users\lutzl\Desktop\otis2\node_modules\discord.js\src\client\websocket\WebSocketShard.js:301:10)
    at WebSocket.onMessage (C:\Users\lutzl\Desktop\otis2\node_modules\ws\lib\event-target.js:132:16)
    at WebSocket.emit (node:events:376:20)`

The mentioned line of filter.js is `const filterToUpdate = client.filters.find((x) => x.toLowerCase() === args[0].toLowerCase());`.

**Comment by ZerioDev** [comment]
Good evening 👋 

Did you leave the filters in the `bot.js` configuration file ? 
Or did you not remove the `client.filters` line in the `index.js` file ?

Have a nice evening !

**Comment by lucasfortheday** [comment]
Good evening 

This is my `bot.js` file. I never touched the filters mentioned there: 

`module.exports = {
    emojis: {
        off: ':x:',
        error: ':warning:',
        queue: ':bar_chart:',
        music: ':musical_note:',
        success: ':white_check_mark:',
    },

    discord: {
        token: 'u98287382173287',
        prefix: '!',
        activity: 'made with github.com/ZerioDev/Music-bot | !help',
    },

    flters: ['8D', 'gate', 'haas', 'phaser', 'treble', 'tremolo', 'vibrato', 'reverse', 'karaoke', 'flanger', 'mcompand', 'pulsator', 'subboost', 'bassboost', 'vaporwave', 'nightcore', 'normalizer', 'surrounding'],
    
       
    ownerID: "2197392179837"
      
};`

Also, here's the `client.filters` line: `client.filters = client.config.filters;`

**Comment by ZerioDev** [comment]
Good evening 👋

In your provided code i can see `flters` but it's `filters`.

Have a nice evening !
