### ISSUE TITLE
error

### ISSUE THREAD

**Issue by FatihUSHA** [ZerioDev/Music-bot#71]
UnhandledPromiseRejectionWarning: Error: FFmpeg/avconv not found!
    at Function.getInfo (C:\Users\Acer\Desktop\muzikbotu deneme\node_modules\prism-media\src\core\FFmpeg.js:142:11)
    at Function.create (C:\Users\Acer\Desktop\muzikbotu deneme\node_modules\prism-media\src\core\FFmpeg.js:155:38)
    at new FFmpeg (C:\Users\Acer\Desktop\muzikbotu deneme\node_modules\prism-media\src\core\FFmpeg.js:44:27)
    at StreamDownloader (C:\Users\Acer\Desktop\muzikbotu deneme\node_modules\discord-ytdl-core\index.js:45:24)
    at C:\Users\Acer\Desktop\muzikbotu deneme\node_modules\discord-player\src\Player.js:681:31
    at new Promise (<anonymous>)
    at Player._playYTDLStream (C:\Users\Acer\Desktop\muzikbotu deneme\node_modules\discord-player\src\Player.js:667:16)
    at Player._playTrack (C:\Users\Acer\Desktop\muzikbotu deneme\node_modules\discord-player\src\Player.js:747:14)
    at C:\Users\Acer\Desktop\muzikbotu deneme\node_modules\discord-player\src\Player.js:300:22
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:9152) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
(node:9152) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by FatihUSHA** [comment]
please help me !!

**Comment by ZerioDev** [comment]
Hello 👋

Do you have ffmpeg ?
If you already have ffmpeg, install `ffpmeg-static` from NPM.

Have a nice day !

**Comment by FatihUSHA** [comment]
i did it now
thank you for codes bro
you are the king

**Comment by ZerioDev** [comment]
Np, have a nice day 👍
