### ISSUE TITLE
Skip command error

### ISSUE THREAD

**Issue by Sintzy** [ZerioDev/Music-bot#89]
`
(node:404) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'name' of null
    at module.exports (/home/runner/MusicLab/player/trackStart.js:2:121)
    at Player.emit (events.js:315:20)
    at Player.EventEmitter.emit (domain.js:483:12)
    at /home/runner/MusicLab/node_modules/discord-player/src/Player.js:748:34
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at runNextTicks (internal/process/task_queues.js:66:3)
    at listOnTimeout (internal/timers.js:518:9)
    at processTimers (internal/timers.js:492:7)
(node:404) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:404) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.`

**Comment by ZerioDev** [comment]
You need to update `discord-player` with the command : `npm i discord-player`  !

**Comment by Sintzy** [comment]
> You need to update `discord-player` with the command : `npm i discord-player` !

tnx

**Comment by ZerioDev** [comment]
Problem solved, i close the issue 👍
